
kind: wasmer.io/App.v0
name: todo
description: Simple PHP Todo Application

runtime: php
php_version: 8.3

build:
  commands: []

start:
  command: php -S 0.0.0.0:8000 -t .

environment:
  APP_ENV: production
  APP_DEBUG: "false"

database:
  type: mysql
  version: 8.4

scaling:
  mode: single_concurrency
